name: build an test feature branch
on:
  push:
    branches:
      - feature/*
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull and checkout from git repository
        run: |
          echo "pulling and cheking out from git repository"
      
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install npm packages
        run: npm install

      - name: Install Angular version
        run: npm install -g @angular/cli@latest

      - name: Run tests and build version
        run: |
          ng test --watch=false
          ng build
          echo "run test and build angular app"
      
